### ISSUE TITLE
BeanDefinitionParsingException

### ISSUE THREAD

**Issue by gvsharma** [piomin/sample-spring-kotlin-microservice#2]
i am trying to build this project and getting below error.[here](https://stackoverflow.com/questions/48544015/intellij-idea-2017-3-unable-to-start-kotlin-spring-boot-app-configuration-cla) i found the probable reasons but none of the solutions are working. 

Here is the Exception log.

```
2019-10-04 12:43:40.743[0;39m [32m INFO[0;39m [35m12734[0;39m [2m---[0;39m [2m[           main][0;39m [36mpleSpringKotlinMicroserviceApplicationKt[0;39m [2m:[0;39m No active profile set, falling back to default profiles: default
[2m2019-10-04 12:43:41.211[0;39m [33m WARN[0;39m [35m12734[0;39m [2m---[0;39m [2m[           main][0;39m [36mConfigServletWebServerApplicationContext[0;39m [2m:[0;39m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: @Configuration class 'SwaggerConfig' may not be final. Remove the final modifier to continue.
Offending resource: class path resource [pl/piomin/services/config/SwaggerConfig.class]
[2m2019-10-04 12:43:41.221[0;39m [32m INFO[0;39m [35m12734[0;39m [2m---[0;39m [2m[           main][0;39m [36mConditionEvaluationReportLoggingListener[0;39m [2m:[0;39m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2m2019-10-04 12:43:41.227[0;39m [31mERROR[0;39m [35m12734[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application run failed

org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: @Configuration class 'SwaggerConfig' may not be final. Remove the final modifier to continue.
Offending resource: class path resource [pl/piomin/services/config/SwaggerConfig.class]
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:72) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClass.validate(ConfigurationClass.java:217) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.validate(ConfigurationClassParser.java:208) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at pl.piomin.services.SampleSpringKotlinMicroserviceApplicationKt.main(SampleSpringKotlinMicroserviceApplication.kt:15) [classes/:na]
```

**Comment by gvsharma** [comment]
by making below changes , am able to run the app now.
1. adding this annotaion in `SwaggerConfig` class @Profile("dev")
2.1: make `SampleSpringKotlinMicroserviceApplication` `open` 
or
2.2 Remove @SpringBootApplication annotation in `SampleSpringKotlinMicroserviceApplication` and add below two annotaions.
`@EnableAutoConfiguration
@ComponentScan`

**Comment by piomin** [comment]
It's pretty interesting. I don't have such error when I'm running the app. How are you running it?
